<?php

/**
 * @file
 * Contains ucsb_login_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function ucsb_login_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ucsb_login_page module.
    case 'help.page.ucsb_login_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Login page for UCSB accounts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ucsb_login_page_theme() {
  return [
    'ucsb_login_page' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 * Remove all tabs from user login form
 */
function ucsb_login_page_menu_local_tasks_alter(&$data, $route_name) {
    if($route_name == 'user.login'  && isset($data['tabs'][0])) {
        foreach ($data['tabs'][0] as $key => $tab){
            $data['tabs'][0][$key]['#access'] = FALSE;
        }
    }
}