<?php

/**
 * @file
 * Contains ucsb_login_page.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Config\FileStorage;

/**
 * Implements hook_help().
 */
function ucsb_login_page_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the ucsb_login_page module.
    case 'help.page.ucsb_login_page':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Login page for UCSB accounts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function ucsb_login_page_theme() {
  return [
    'ucsb_login_page' => [
      'render element' => 'children',
    ],
  ];
}

/**
 * Implements hook_menu_local_tasks_alter().
 * Remove all tabs from user login form
 */
function ucsb_login_page_menu_local_tasks_alter(&$data, $route_name) {
    if($route_name == 'user.login'  && isset($data['tabs'][0])) {
        foreach ($data['tabs'][0] as $key => $tab){
            $data['tabs'][0][$key]['#access'] = FALSE;
        }
    }
}

/**
 * Implements hook_preprocess_page().
 * Prepare the variables for the template
 */
function ucsb_login_page_preprocess_page(&$variables) {
    $route_name = \Drupal::routeMatch()->getRouteName();
    if($route_name == 'user.login') {
        // You will most likely want to show and render the form for anonymous users.
        $login_form = false;
        if (\Drupal::currentUser()->isAnonymous()) {
            $login_form = \Drupal::formBuilder()->getForm(Drupal\user\Form\UserLoginForm::class);
        }
        $variables['login_form'] = $login_form;
        // if cas module is enabled then create flag
        $cas_enabled = false;
        if (\Drupal::moduleHandler()->moduleExists('cas')) {
            $cas_enabled = true;
        }
        $variables['cas_enabled'] = $cas_enabled;
    }
}